FROM node:lts-alpine AS frontend-build

RUN apk add --no-cache git
RUN git clone https://github.com/AVecsi/yivi-frontend-packages.git /frontend-src
WORKDIR /frontend-src
RUN npm install && npm run build
WORKDIR /frontend-src/examples/browser/yivi-frontend
RUN npm install

FROM golang:1 as build

# Set build environment
ENV CGO_ENABLED=1

RUN apt-get update && apt-get install -y gcc curl git make

# Install Rust
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Build irma CLI tool
COPY . /irmago
WORKDIR /irmago

# Build pq-gabi's Rust dependency before go build
RUN go mod download && \
    cd /go/pkg/mod/github.com/\!a\!vecsi/pq-gabi@$(go list -m -f '{{.Version}}' github.com/AVecsi/pq-gabi) && \
    chmod -R u+w . && \
    make build

RUN go build -a -ldflags '-extldflags "-static -lm"' -o "/bin/irma" ./irma

# Create application user
RUN useradd -u 1000 -ms /bin/bash irma

# Use the build stage directly as the final image so all libraries are available
FROM build

# Copy built frontend
COPY --from=frontend-build /frontend-src /frontend

# Include schemes as assets in the Docker image to speed up the start-up time
RUN /bin/irma scheme download --use-schemes-assets-path

ENTRYPOINT ["/bin/irma"]